/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef WSAUTOCLICK_V3_3_PRIVATE_H
#define WSAUTOCLICK_V3_3_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"3.0.1.236"
#define VER_MAJOR	3
#define VER_MINOR	0
#define VER_RELEASE	1
#define VER_BUILD	236
#define COMPANY_NAME	""
#define FILE_VERSION	"3.3"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	""

#endif /*WSAUTOCLICK_V3_3_PRIVATE_H*/
